### PR TITLE
Syntax

### LINKED ISSUE #23: 0.8.12, #ifndef, #else, #endif have mixed colors
#ifndef has the same color of #define while #else and #endif have the # sign colored like #define but else and endif are colored like "normal" if else endif both in .ch and .prg files.
Is it expected?

### PR DESCRIPTION
**Pull request by edgardmessias**
* Improved preprocessors (close #23)
* Improved syntax for multiline string with pragma
* Added syntax for **TEXT INTO** and **TEXT TO VAR**
* Fixed syntax for **IN** keyword
* Fixed syntax for "**STATIC FUNCTION**"
* Fixed syntax for name in method and class

### CODE REVIEW

**Comment by edgardmessias** [comment]
@APerricone , I like to test on this theme: https://marketplace.visualstudio.com/items?itemName=uloco.theme-bluloco-dark

**Comment by edgardmessias** [comment]
image
image

**Comment by APerricone** [comment]
Hello, a little thing: `#pragma __endtext` and `ENDTEXT` are interchangable.
It is because in my tmlanguage we have:
```javascript
 "end": "(?i:^\\s*(#\\s*pragma)\\s+(__endtext)|(ENDTEXT)\\s*$)",
```

**Comment by edgardmessias** [comment]
Nice, I will fix

**Comment by edgardmessias** [comment]
@APerricone, done.

**Comment by APerricone** [comment]
I done some modification, update your code

**Comment by edgardmessias** [comment]
@APerricone, instead of `"include": "source.harbour"`, you can use `"include": "$base"`

**Comment by APerricone** [comment]
I don't know where $base come from, but in C/C++ syntax created a lot of problem, that are visible in our integration too, see https://github.com/atom/language-c/issues/146
At most we can use $self that is present in the documentation https://macromates.com/manual/en/language_grammars

**Pull request merged**
