### PR TITLE
Update harbour.tmLanguage.json

### PR DESCRIPTION
**Pull request by edgardmessias**

### CODE REVIEW

**Comment by APerricone** [comment]
Sorry, Why should we use this tmlanguage? Who did it? It looks like a copy of another that does not reflect the harbour syntax

**Comment by edgardmessias** [comment]
> Why should we use this tmlanguage?

Is used at my work

> Who did it?

I did it

> It looks like a copy of another that does not reflect the harbour syntax

Yes, reflect the harbour syntax, but some improvements, like:

* Class/Method declaration
* Parameters
* Codeblocks

Get better by using https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

**Comment by APerricone** [comment]
I see It has some interesting things, I am testing it and probably I will merge this branch.
Did you start from mine? the "c_code" patterns are the same...

**Comment by edgardmessias** [comment]
Yes, I started with your code.

Merged some syntax ideas from:
https://github.com/Microsoft/vscode/tree/master/extensions/cpp/syntaxes
https://github.com/Microsoft/vscode/tree/master/extensions/typescript-basics/syntaxes
https://github.com/Microsoft/vscode/tree/master/extensions/java/syntaxes

**Comment by edgardmessias** [comment]
The hard work was the ";", nammed with `#continue-expression`

**Pull request merged**
