### PR TITLE
A solution for: EMFILE: too many open files

### PR DESCRIPTION
**Pull request by clgeraldo**
A solution for the error: "EMFILE: too many open files"

### CODE REVIEW

**Comment by clgeraldo** [comment]
This is one solution that I'm using in my VSCode.

**Comment by APerricone** [comment]
hello, thank you for your pull request, I see your fix, but I will not include it on my code for 2 reasons: all my code is in English, so the Spanish function name is out of context, for second the JavaScript promise technology was made to avoid the "callback hell", in this fix I will going to use the "then" function. I will include a similar fix asap. regards

**Comment by clgeraldo** [comment]
You're right.
I didn't really remember to change the function to English.
And I don't have much knowledge of JavaScript.
I hope I have contributed in some way.
Thanks.

**Comment by APerricone** [comment]
I did my version of your fix, see https://github.com/APerricone/harbourCodeExtension/commit/fbd7e64ba7e28c12ccd98645ec7cfac66e0412c0

**Comment by clgeraldo** [comment]
Ok.
I saw this and think it's good.
Congratulations.
Thank's so much.

**Pull request closed without merging**
